### ISSUE TITLE
PH1. Differentiate

### ISSUE THREAD

**Issue by rslruiz** [Hazlll/oo3ThorProject#1]
List similar apps and differentiate your project.

**Comment by Hazlll** [comment]
Similar apps: mint , Pocket Guard
Diffenrences:The project is more  focuses on calculating savings over time, tracking daily expenses, and providing insights into spending habits. Additional features like a virtual piggy bank simulation, savings growth graphs, expense reports, and setting monthly challenges with rewards. 

 mint  and  Pocket Guard are Software for managing expenses, evaluating finances, and keeping track of investments that also include features like bill reminders, credit score tracking, receipt scanning, and envelope-based budgeting
